steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/roi-mb-appuser13/venusupdate:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/roi-mb-appuser13/venusupdate:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'venusupdate',
        '--image=gcr.io/roi-mb-appuser13/venusupdate:$SHORT_SHA',
        '--region=us-central1',
      ]
